### ISSUE TITLE
[Incompatibility: Fabric]: ViaFabricPlus

### ISSUE THREAD

**Issue by TayouVR** [Tuinity/Moonrise#65]
### Minecraft Version

1.21.1

### Moonrise Version

0.1.0-beta.8+68ea18b from modrinth

### Mod Loader

Fabric

### Logs and Crash Reports

```
[08:35:45] [main/ERROR]: Mixin apply for mod viafabricplus failed viafabricplus.mixins.json:fixes.minecraft.entity.MixinEntity from mod viafabricplus -> net.minecraft.class_1297: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/class_1297::fixBlockCollisionMargin with priority 1000 cannot inject into net/minecraft/class_1297::method_5852()V merged by ca.spottedleaf.moonrise.mixin.collisions.EntityMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> viafabricplus.mixins.json:fixes.minecraft.entity.MixinEntity from mod viafabricplus -> Prepare Injections -> constant$gnc000$viafabricplus$fixBlockCollisionMargin(D)D -> Prepare ->  -> { target: method_5852()V }]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_1297::fixBlockCollisionMargin with priority 1000 cannot inject into net/minecraft/class_1297::method_5852()V merged by ca.spottedleaf.moonrise.mixin.collisions.EntityMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> viafabricplus.mixins.json:fixes.minecraft.entity.MixinEntity from mod viafabricplus -> Prepare Injections -> constant$gnc000$viafabricplus$fixBlockCollisionMargin(D)D -> Prepare ->  -> { target: method_5852()V }]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75) [libjf-unsafe-v0-3.17.3-b2c8b7bb9bb9f239.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at knot/net.minecraft.class_2966.method_12851(class_2966.java:52) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:130) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.8.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[08:35:45] [main/INFO]: Instancing error handler class dev.isxander.mixinconflicthelper.ConflictErrorHandler
[08:35:45] [main/INFO]: Forking JVM to display Swing GUI (bypass LWJGL)!
```

### Additional Context

ViaFabricPlus version 3.4.9 for 1.21.1
they have a issue tracking the incompatibility here:
https://github.com/ViaVersion/ViaFabricPlus/issues/600

**Comment by jpenilla** [comment]
This is no longer an issue in 1.21.3. Given the nature of ViaFabricPlus as a mod, and their policy of only supporting the latest Minecraft version, I don't think this is something that makes sense for us to spend time on.
